📌 Tarea
Crear un archivo pandas_transformaciones.ipynb con al menos 3 ejemplos propios de:

Creación de nuevas columnas.
Transformaciones con apply() y funciones lambda.
Reemplazo de valores con map() o replace().

In [29]:
import pandas as pd
#creamos el data frame base
empleados = pd.DataFrame({
    "Nombre": ["Ana", "Luis", "Carlos", "María", "Jorge"],
    "Edad": [22, 35, 29, 41, 19],
    "Salario_mensual": [9000, 15000, 12000, 18000, 8000],
    "Genero": ["F", "M", "M", "F", "M"]
})

empleados

   Nombre  Edad  Salario_mensual Genero
0     Ana    22             9000      F
1    Luis    35            15000      M
2  Carlos    29            12000      M
3   María    41            18000      F
4   Jorge    19             8000      M

In [30]:
#creamos nueva columna (salario anual)

empleados["Salario_anual"] = empleados["Salario_mensual"] * 12
empleados

   Nombre  Edad  Salario_mensual Genero  Salario_anual
0     Ana    22             9000      F         108000
1    Luis    35            15000      M         180000
2  Carlos    29            12000      M         144000
3   María    41            18000      F         216000
4   Jorge    19             8000      M          96000

In [31]:
#creamos una columna donde categorice por edades

empleados["Categoria_edad"] = empleados["Edad"].apply(
    lambda x: "Joven" if x < 30 else "Adulto"
)

empleados

   Nombre  Edad  Salario_mensual Genero  Salario_anual Categoria_edad
0     Ana    22             9000      F         108000          Joven
1    Luis    35            15000      M         180000         Adulto
2  Carlos    29            12000      M         144000          Joven
3   María    41            18000      F         216000         Adulto
4   Jorge    19             8000      M          96000          Joven

In [32]:
empleados["Genero_completo"] = empleados["Genero"].replace({
    "F": "Femenino",
    "M": "Masculino"
})

empleados

,Nombre,Edad,Salario_mensual,Genero,Salario_anual,Categoria_edad,Genero_completo
0,Ana,22,9000,F,108000,Joven,Femenino
1,Luis,35,15000,M,180000,Adulto,Masculino
2,Carlos,29,12000,M,144000,Joven,Masculino
3,María,41,18000,F,216000,Adulto,Femenino
4,Jorge,19,8000,M,96000,Joven,Masculino