📌 Tarea
Crear un archivo pandas_filtrado.ipynb con al menos 5 ejemplos propios de filtrado avanzado.

In [1]:
import pandas as pd
#Primero creamos el data frame para los ejemplos

empleados = pd.DataFrame({
    "Nombre": ["Ana", "Luis", "Marcos", "Sofía", "Daniel", "Karla", "Jorge", "Elena"],
    "Edad":   [28, 35, 42, 30, 25, 33, 45, 29],
    "Salario": [12000, 18000, 9500, 22000, 8000, 16000, 30000, 11000],
    "Departamento": ["Ventas", "TI", "Recursos Humanos", "Marketing", "TI", "Ventas", "Dirección", "Marketing"]
})

empleados

   Nombre  Edad  Salario      Departamento
0     Ana    28    12000            Ventas
1    Luis    35    18000                TI
2  Marcos    42     9500  Recursos Humanos
3   Sofía    30    22000         Marketing
4  Daniel    25     8000                TI
5   Karla    33    16000            Ventas
6   Jorge    45    30000         Dirección
7   Elena    29    11000         Marketing

In [2]:
#ejemplo 1 Filtrar empleados con salario mayor a $10,000

empleados[empleados["Salario"] > 10000]

  Nombre  Edad  Salario Departamento
0    Ana    28    12000       Ventas
1   Luis    35    18000           TI
3  Sofía    30    22000    Marketing
5  Karla    33    16000       Ventas
6  Jorge    45    30000    Dirección
7  Elena    29    11000    Marketing

In [3]:
#ejemplo 2 Filtrar empleados con edad mayor a 30 y salario mayor a $15,000

empleados[(empleados["Edad"] > 30) & (empleados["Salario"] > 15000)]

  Nombre  Edad  Salario Departamento
1   Luis    35    18000           TI
5  Karla    33    16000       Ventas
6  Jorge    45    30000    Dirección

In [4]:
#ejemplo 3 Filtrar empleados que NO sean del departamento de TI

empleados[empleados["Departamento"] != "TI"]

   Nombre  Edad  Salario      Departamento
0     Ana    28    12000            Ventas
2  Marcos    42     9500  Recursos Humanos
3   Sofía    30    22000         Marketing
5   Karla    33    16000            Ventas
6   Jorge    45    30000         Dirección
7   Elena    29    11000         Marketing

In [5]:
#ejemplo 4 Empleados entre 25 y 35 años

empleados[(empleados["Edad"] >= 25) & (empleados["Edad"] <= 35)]

   Nombre  Edad  Salario Departamento
0     Ana    28    12000       Ventas
1    Luis    35    18000           TI
3   Sofía    30    22000    Marketing
4  Daniel    25     8000           TI
5   Karla    33    16000       Ventas
7   Elena    29    11000    Marketing

In [6]:
#ejemplo 5 Filtrar empleados cuyo nombre empieza con la letra “A” o “E”

empleados[empleados["Nombre"].str.startswith(("A", "E"))]

  Nombre  Edad  Salario Departamento
0    Ana    28    12000       Ventas
7  Elena    29    11000    Marketing