Tarea 
crear un archivo pandas_dataframe.ipynb con un mini DataFrame de 10 registros propios.

In [1]:
import pandas as pd

# Crear DataFrame con 10 estudiantes
estudiantes = pd.DataFrame({
    "Nombre": [
        "María López", "Saulo Raya", "Ana Torres", "Luis Pérez", "Karla Jiménez",
        "Pedro Gómez", "Sofía Cruz", "Daniel Martínez", "Valeria Soto", "Jorge Álvarez"
    ],
    "Edad": [20, 22, 19, 21, 20, 23, 18, 24, 19, 22],
    "Carrera": [
        "Relaciones Comerciales", "Ciencia de Datos", "Contaduría", "Administración",
        "Mercadotecnia", "Ingeniería Industrial", "Negocios Internacionales",
        "Economía", "Gastronomía", "Comercio Internacional"
    ]
})

estudiantes

            Nombre  Edad                   Carrera
0      María López    20    Relaciones Comerciales
1       Saulo Raya    22          Ciencia de Datos
2       Ana Torres    19                Contaduría
3       Luis Pérez    21            Administración
4    Karla Jiménez    20             Mercadotecnia
5      Pedro Gómez    23     Ingeniería Industrial
6       Sofía Cruz    18  Negocios Internacionales
7  Daniel Martínez    24                  Economía
8     Valeria Soto    19               Gastronomía
9    Jorge Álvarez    22    Comercio Internacional

In [2]:
#Mostrar las primeras filas (head())

estudiantes.head()

          Nombre  Edad                 Carrera
0    María López    20  Relaciones Comerciales
1     Saulo Raya    22        Ciencia de Datos
2     Ana Torres    19              Contaduría
3     Luis Pérez    21          Administración
4  Karla Jiménez    20           Mercadotecnia

In [3]:
#Mostrar las últimas filas (tail())

estudiantes.tail()

            Nombre  Edad                   Carrera
5      Pedro Gómez    23     Ingeniería Industrial
6       Sofía Cruz    18  Negocios Internacionales
7  Daniel Martínez    24                  Economía
8     Valeria Soto    19               Gastronomía
9    Jorge Álvarez    22    Comercio Internacional

In [4]:
#Acceder a una columna (por ejemplo, “Nombre”)

estudiantes["Nombre"]

0        María López
1         Saulo Raya
2         Ana Torres
3         Luis Pérez
4      Karla Jiménez
5        Pedro Gómez
6         Sofía Cruz
7    Daniel Martínez
8       Valeria Soto
9      Jorge Álvarez
Name: Nombre, dtype: object

In [5]:
#Acceder a una fila específica (por ejemplo, fila 3)

estudiantes.loc[3]

Nombre         Luis Pérez
Edad                   21
Carrera    Administración
Name: 3, dtype: object

In [6]:
#otra forma de acceder a una fila especifica (por ejemplo, fila 4)

estudiantes.iloc[4]

Nombre     Karla Jiménez
Edad                  20
Carrera    Mercadotecnia
Name: 4, dtype: object